# Generated by Django 4.2.4 on 2024-02-02 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_notifications', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('profile_visibility', models.CharField(default='public', max_length=20)),
                ('content_visibility', models.CharField(default='public', max_length=20)),
                ('wi_fi_only', models.BooleanField(default=True)),
                ('video_quality', models.CharField(default='medium', max_length=20)),
                ('audio_quality', models.CharField(default='medium', max_length=20)),
                ('app_language', models.CharField(default='english', max_length=20)),
                ('region', models.CharField(default='us', max_length=20)),
                ('dark_mode', models.BooleanField(default=False)),
                ('download_location', models.CharField(default='internal', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
