# Generated by Django 4.2.4 on 2024-02-19 05:24

from django.db import migrations, models
import mediaManager.models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='color',
            field=models.CharField(default=mediaManager.models.generate_random_color, max_length=7),
        ),
        migrations.AddField(
            model_name='album',
            name='icon',
            field=models.CharField(default='ios-people', max_length=30),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='user_uploads/'),
        ),
    ]
