# Generated by Django 4.2.4 on 2024-02-18 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_customuser_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
    ]
