# Generated by Django 4.2.4 on 2024-02-18 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_remove_tag_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='UserTag',
        ),
    ]
